name: Laravel

on:
  push:
    branches: [ "github-action" ]
  pull_request:
    branches: [ "github-action" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', './src/.env');"
    - name: update dependencies
      working-directory: ./src
      run: composer update
    - name: Install Dependencies
      working-directory: ./src
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      working-directory: ./src
      run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ./src
      run: chmod -R 777 storage bootstrap/cache
    - name: Start mysql service
      run: |
        sudo /etc/init.d/mysql start
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: multi_food_db
        DB_USERNAME: root
        DB_PASSWORD: root
      run: vendor/bin/phpunit
